### PR TITLE
Add developer guide

### LINKED ISSUE #176: Seshat project GitHub workflow proposal & timeline
# Proposal

## Timeline

- July 2024: At minimum, let's try to ensure all development exclusive to the upstream repo is complete
    - [x] **Majid** to continue working on original repo (main `Qing` branch), implementing features unrelated to maps development up until leave, at which point development on this repo should cease, as should updates to the current live site on AWS
    - [x] **Ed** to finalise optimal future-proof GitHub workflow for Seshat project that is robust to personnel changes and can be supported over multiple institutions in the long term (see draft below)
    - [x] **Ed/Kalle** to set up Seshat GitHub organisation and new fork of the Seshat repo hosted here, to which everyone who is a developer should be given access and work from going forwards.
        - Forked from Ed's fork, but ensuring is up to date with Majid's repo too by the time he leaves
        - Transfer project board & issues to the new repo
    - [x] https://github.com/Seshat-Global-History-Databank/seshat/issues/3
        - **Ed/Kalle** to book session(s) with **Majid** towards the end of the month to provide overview of how new GitHub org/workflow will work by the time he returns
2. August/September 2024 (or Majid's leave period); Ed/Kalle
    - #79
    - #91 
    - Implement GH action that pulls main branch to server on successful push (can initially be configured to a test site and later changed to live site)
    - Refactor and document the codebase, perhaps redesign some of the database structure as needed
4. October onwards
    - **Ed** to provide **Majid** hands-on GitHub training (perhaps during Vienna Seshat get-together)
    - **Majid** is able to easily follow documentation to deploy new version of Seshat website via Pulumi
        - Switch the domain to point at new website and spin down the old one
    - Development to continue as per the documented workflow

This timeline proposal means that the maps won't go live on the main Seshat website until after Majid returns, which is something we should check with Pieter. If this isn't feasible, we could work on #79 in July (or just make an AWS version of what we currently have) and then just schedule a day to set it up with Majid on a call in July.

## GitHub workflow

- Simple main branch and feature/bug branches
- Process must enable Majid to continue to be able to support rapid deployment of new features
- CI deployment to staging, manual git pull to production

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
Adding an initial development guide to the project documentation.

This PR:
- Closes https://github.com/edwardchalstrey1/seshat/issues/176
- Covers how to use issues, project board and the GitHub workflow for Seshat
- Does *not* include how to update the live website - I have added a placeholder link TODO for another page that can explain that once we have determined exactly how it will work in the long run

Reviewers should:
- Check the workflow makes sense and comment if anything is unclear or should change
- @MajidBenam  note: you can [build the docs locally](https://github.com/Seshat-Global-History-Databank/seshat?tab=readme-ov-file#developers) or just look at the Files changed tab here in the PR
- Question for @kallewesterling - are the docs live on GitHub pages already? If not, would be good to enable that and also have a docs preview link to generate on a PR

### CODE REVIEW

**Comment by kallewesterling** [comment]
They are live already! See deployments here: https://github.com/Seshat-Global-History-Databank/seshat/deployments/github-pages

And here's the GitHub rendering: https://seshat-global-history-databank.github.io/seshat/

**Review by kallewesterling — CHANGES_REQUESTED** [review]
Perhaps we should keep TODOs in comments? 

The way to do that in RST is:

```rst
..
    The comment goes here.
```

**Comment by kallewesterling** [comment]
Otherwise all good, I think!

**Comment by edwardchalstrey1** [comment]
@kallewesterling I also removed info from the README that is now duplicated in the docs

**Comment by edwardchalstrey1** [comment]
@kallewesterling do you know why the docs action is cancelled on push? Seems it has passed for pull_request

**Pull request merged**
