### PR TITLE
Restructure Seshat docs according to roles

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
- Restructures the docs based on the role of the person viewing the docs with explanations of who those people are
- This structure will serve the completion of these issues better
    - https://github.com/edwardchalstrey1/seshat/issues/91
    - #57 
- Adds RTD theme

Screenshot 2024-08-15 at 16 18 40

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
Update: I have asked Pieter Francois to comment on the role definitions via email

**Comment by kallewesterling** [comment]
I wonder if RTD theme might look "too technical" to some of the potential users..

**Review by kallewesterling — APPROVED** [review]
Looks great to me!

**Comment by edwardchalstrey1** [comment]
> I wonder if RTD theme might look "too technical" to some of the potential users..

I had a look at some other themes but none looked particularly extra-friendly to me :)

**Pull request merged**
