### PR TITLE
[IDEA - DO NOT MERGE] Visualise uncertainty by differential blurring of polity shapes

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
This PR is a first attempt towards #20 

### Visualising uncertainty

- Adds a "confidence" field which takes values of 1, 2 or 3. Where 1 indicates a border shape is 'Approximate', 2 means 'Moderately precise' and 3 means 'Determined by international law'. 
    - I have taken this idea from the measure used by [historical basemaps](https://github.com/aourednik/historical-basemaps?tab=readme-ov-file#polygons) 
- Sets the amount of blur applied to shapes (on polity pages and the world map) based on the confidence score, with 1 being the most blurry and 3 the least. Where the confidence field is not filled in (in every case currently), there are confidence values set by some logic based on the polity start year:
    - `If polity start year is less than 0: confidence = 1` | `If polity start year is greater than 0 and less than 1500: confidence = 2` | `If polity start year is greater than 1500: confidence = 3`
- On Polity pages (and crucially on the edit page), you can click a polity to reveal it's ID number and confidence score, and also there's a button to show all the shapes with their respective IDs and confidence scores. This provides a way to indicate a shape when suggesting edits to the confidence via the existing edit mechanism
    - The specifics of the edit mechanism can be worked on later, see #32 
    - The question of whether the confidence value itself should be an editable field, or should be determined by the "amount" of evidence for a shape is an open question - see #20 
 
### Other changes

- Renames the `Videoshapefile` model to `Cliopatria`
- The legend no longer scrolls of screen when you click many polities, instead it becomes scrollable

### Reviewers

Take a look at the [world map](http://51.141.239.61:8000/core/world_map) now and notice how it looks different, with the blur levels of shapes based on the uncertainty scoring as outlined above.
 
This change is the most noticeable on the world map but is also applied on individual Polity pages.
 
Here are some Polity page examples for each of the confidence levels:
[Seleucids](http://51.141.239.61:8000/core/polity/108) (1)
[Roman Empire - Dominate](http://51.141.239.61:8000/core/polity/71) (2)
[Republic of China](http://51.141.239.61:8000/core/polity/784) (3)

### CODE REVIEW

**Comment by edwardchalstrey1** [comment]
@kallewesterling I'm not sure why but the last 2 commits ([7866eb9](https://github.com/Seshat-Global-History-Databank/seshat/pull/43/commits/7866eb9d2cb7ef09e0e4f1cb7a0f49dc99a02b84), [c013fee](https://github.com/Seshat-Global-History-Databank/seshat/pull/43/commits/c013feeab7da769d6c1e465f43065e3dfafd421a)) seem to break the site when I run `gunicorn` when I run this branch on http://51.141.239.61:8000/ - can you spot anything I've done wrong? 

Running locally it works, but when I look at http://localhost:8000/api/ I can't see core/cliopatria

**Comment by kallewesterling** [comment]
@edwardchalstrey1 I think I can see this all on the dev server, which may be the easiest way for me to look at this without having to migrate my local database before we've merged the edits.

It looks good, I think, but I'm not loving the blurriness. I wonder if we should run this by the larger team, and if there's a better way to show the uncertainty? Maybe by creating dashed borders or something?

**Comment by edwardchalstrey1** [comment]
> @edwardchalstrey1 I think I can see this all on the dev server, which may be the easiest way for me to look at this without having to migrate my local database before we've merged the edits.
> 
> It looks good, I think, but I'm not loving the blurriness. I wonder if we should run this by the larger team, and if there's a better way to show the uncertainty? Maybe by creating dashed borders or something?

Fair enough! Yes, I've emailed Pieter, Peter and Jim on the 26th July but haven't had any responses yet - perhaps I'll but the word out on the Data/Culture channel too

**Comment by rwood-97** [comment]
lgtm :)

**Comment by kmcdono2** [comment]
> Do you think the 1-3 uncertainty score works well?

> Where the confidence field is not filled in (in every case currently), there are confidence values set by some logic based on the polity start year:
> If polity start year is less than 0: confidence = 1 | If polity start year is greater than 0 and less than 1500: confidence = 2 | If polity start year is greater than 1500: confidence = 3

Uncertainty based only on date of polity "start" is a) not the only kind of uncertainty, b) unclear for whom there is uncertainty and c) why there is uncertainty. Simply being 'old' is not the source of uncertainty for most frontiers/borders. Are there other attributes for polities that could complicate how uncertainty is assigned? E.g. how many sources attest this border geometry? How reliable are those sources?


> Do you think the different blur levels work well to illustrate this?

One of the problems with using vector polygons to represent historical polities is that the concept of the border as a defined line in the landscape simply does not exist in most parts of the world before the 19th c. Blur helps communicate the idea of a frontier space, which is more accurate for most cultures, but how much should be 'solid' and how wide should the 'blur' be? Also the idea that polities have the same level of control over everything 'within' the polygon is a fiction, and the blur on the edges doesn't communicate this.

> How would you set the default years for the uncertainty scores?

I don't think years are the main issue in determining uncertainty (see above).

**Comment by PieterFrancois** [comment]
Hi Ed, 

Good to see this progress.

A few quick observations from me:
- Not fully sold on using years as the main arbiter of uncertainty. I think we need to go to all our experts and ask them for a number (o, 1, 2, and 3) which means we need agreement and guidelines on what these mean so that there is rough comparability between the codes. This also allows for different experts present us with different numbers and we should capture this. That way the spatial data is in line with all our other data. 
- I am OK with using blur at the edges as a shorthand for 'be careful to treat these lines as well delineated and set in stone'. The intellectual reservations are well known but at the same time we want to do more than throw our hands up in the air. In the methodology paper I will have to explain this clearly and we also need to find a way to communicate this well and prominently on the website. However, I don't particularly like the specific blurness. Could you keep the centre clear and use for the border areas a sort of zebra crossing look with one colour the colour of the polity and one colour to signify the level of uncertainty (e.g. white for a bit of uncertainty and dark grey for a lot of uncertainty). 

FYI: Do not wait for Peter's input on this as he is out of action for a while. 

Best, 
Pieter

**Comment by edwardchalstrey1** [comment]
Thanks for your input on this everyone - ok, I think this requires further discussion rather than merging right away - I'll put it on the agenda for the Seshat meeting next week

**Review by kallewesterling — APPROVED** [review]
I think, following our conversation this week, that there is some more experimentation that needs to happen around the visual representation, but otherwise, the implementation looks good to me.

**Pull request closed without merging**
