### PR TITLE
Reintroduce selected date to polity page map

### LINKED ISSUE #198: 🐛 [BUG] - Year does not update on polity pages when moving slider
### Description

See #190 

### Reproduction steps

Navigate to a polity page map and adjust the year with slider

### Screenshots

Before and after bug introduced screenshots:

Screenshot 2024-12-05 at 10 26 18
Screenshot 2024-12-05 at 10 26 09

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### Definition of Done

- [ ] A fix for the bug has been developed on a branch.
- [ ] The bug fix branch has been tested in the Staging website.
- [ ] A pull request has been created for the new branch to be merged into the dev branch.

### PR DESCRIPTION
**Pull request by edwardchalstrey1**
Fixes #198 

@MajidBenam @Zsajk what do you think about this solution? It fixes the bug introduced - you can now hit enter to set the year, and it reintroduces the selected date year in the top left, but makes it clearer that this is the displayed year on the map:

Screenshot 2024-12-05 at 14 53 14

### CODE REVIEW

**Comment by Zsajk** [comment]
Does it also update the year in the select year box when you move the slider like it works on the world map?

**Comment by edwardchalstrey1** [comment]
> Does it also update the year in the select year box when you move the slider like it works on the world map?

Yes exactly

**Comment by Zsajk** [comment]
> > Does it also update the year in the select year box when you move the slider like it works on the world map?
> 
> Yes exactly

Great, thanks

**Comment by MajidBenam** [comment]
I also changed the color to see how things work if I change something on a PR request. :)

**Pull request merged**
